-- --------------------------------------------------------
-- Migration: Create 'trust_signal_audits' table for detailed GEO & Trust Signal data
-- Date: 2026-08-19
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.trust_signal_audits (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_id bigint NOT NULL REFERENCES public.runs(id) ON DELETE CASCADE,
    hospital_code text REFERENCES public.hospitals(hospital_code),
    target_url text NOT NULL,
    total_score integer NOT NULL DEFAULT 0,
    grade text NOT NULL DEFAULT '보통',
    geo_rate double precision NOT NULL DEFAULT 0.0,
    
    -- 4대 영역별 집계 점수
    crawler_score integer NOT NULL DEFAULT 0,    -- A. AI 크롤러 접근성 (25점 만점)
    schema_score integer NOT NULL DEFAULT 0,     -- B. 구조화 데이터 Schema.org (30점 만점)
    content_score integer NOT NULL DEFAULT 0,    -- C. 신뢰 콘텐츠 자산 (25점 만점)
    technical_score integer NOT NULL DEFAULT 0,  -- D. 기술적 AI 가독성 (20점 만점)
    
    -- 4대 영역별 원천 세부 데이터 (점수, 텍스트 스니펫, 링크, 원본 JSON 등)
    crawler_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    schema_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    content_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    technical_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    
    -- 전체 진단 리포트 원본 백업
    full_report_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_trust_signal_audits_run_id ON public.trust_signal_audits(run_id);
CREATE INDEX IF NOT EXISTS idx_trust_signal_audits_hospital_code ON public.trust_signal_audits(hospital_code);

-- 1. 필수 권한 부여 (401 Unauthorized 방지)
GRANT ALL ON TABLE public.trust_signal_audits TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.trust_signal_audits_id_seq TO anon, authenticated, service_role;

-- 2. RLS (Row Level Security) 활성화 및 전체 정책 허용
ALTER TABLE public.trust_signal_audits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access to trust_signal_audits" ON public.trust_signal_audits;
CREATE POLICY "Allow full access to trust_signal_audits" 
ON public.trust_signal_audits FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);

-- 3. PostgREST 스키마 캐시 즉시 갱신
NOTIFY pgrst, 'reload schema';

