-- 
-- PostgreSQL schema for lua_visibility_web 
--

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------
-- Table Structure for 'hospitals'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hospitals (
    hospital_code text PRIMARY KEY,
    name text NOT NULL,
    director_name text,
    phone text,
    mobile text,
    email text,
    address text,
    homepage text,
    created_at text,
    updated_at text
);

-- --------------------------------------------------------
-- Table Structure for 'hospital_config_versions'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hospital_config_versions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hospital_code text NOT NULL REFERENCES public.hospitals(hospital_code),
    version text NOT NULL,
    aliases text,
    region_terms text,
    competitors text,
    queries text,
    is_active boolean DEFAULT true,
    memo text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- --------------------------------------------------------
-- Table Structure for 'runs'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.runs (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hospital text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    repetitions integer,
    temperature double precision,
    region text,
    device text,
    login_state text,
    hospital_code text REFERENCES public.hospitals(hospital_code),
    config_version text,
    config_version_id bigint REFERENCES public.hospital_config_versions(id),
    ended_at timestamp with time zone,
    status text DEFAULT 'RUNNING',
    total_tasks integer DEFAULT 0,
    completed_tasks integer DEFAULT 0,
    success_rate double precision DEFAULT 0.0,
    overall_mention_rate double precision DEFAULT 0.0,
    result_summary text,
    trust_report_json jsonb
);

-- --------------------------------------------------------
-- Table Structure for 'answers'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.answers (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_id bigint NOT NULL REFERENCES public.runs(id),
    provider text,
    model text,
    query text,
    rep_index integer,
    answer_text text,
    ok boolean DEFAULT false,
    error text,
    mentioned boolean DEFAULT false,
    recommended boolean DEFAULT false,
    first_position integer,
    competitors jsonb,
    measured_at timestamp with time zone,
    search_used boolean DEFAULT false,
    citations jsonb,
    reviewed boolean DEFAULT false,
    review_verdict text,
    task_id text,
    question_id text,
    use_grounding boolean DEFAULT false,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    duration_seconds double precision,
    http_status integer,
    retry_count integer DEFAULT 0,
    status text
);

-- --------------------------------------------------------
-- Table Structure for 'web_verifications'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.web_verifications (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_id bigint REFERENCES public.runs(id),
    hospital_code text NOT NULL REFERENCES public.hospitals(hospital_code),
    hospital_name text NOT NULL,
    platform text NOT NULL,
    verified_at timestamp with time zone NOT NULL,
    verifier_name text DEFAULT 'admin',
    total_questions integer DEFAULT 0,
    matched_questions integer DEFAULT 0,
    match_rate double precision DEFAULT 0.0,
    memo text
);

-- --------------------------------------------------------
-- Table Structure for 'web_verification_answers'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.web_verification_answers (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    verification_id bigint NOT NULL REFERENCES public.web_verifications(id),
    answer_id bigint REFERENCES public.answers(id),
    question_id text,
    query text NOT NULL,
    web_answer_text text,
    web_mentioned boolean DEFAULT false,
    web_recommended boolean DEFAULT false,
    web_competitors jsonb,
    is_matched boolean DEFAULT true,
    difference_reason text,
    verified_at timestamp with time zone
);

-- --------------------------------------------------------
-- Table Structure for 'system_config'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_config (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    key text NOT NULL,
    value jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

-- --------------------------------------------------------
-- Table Structure for 'verification_items'
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.verification_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    answer_id uuid,
    url text,
    is_match boolean DEFAULT false,
    capture_url text,
    raw_text text,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

-- --------------------------------------------------------
-- RLS (Row Level Security) Policies
-- --------------------------------------------------------
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospital_config_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.web_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.web_verification_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_items ENABLE ROW LEVEL SECURITY;

-- Note: Ensure to add appropriate Policies allowing access via anon key for web frontend
CREATE POLICY "Allow public read access to hospitals" ON public.hospitals FOR SELECT USING (true);
CREATE POLICY "Allow public read access to hospital_config_versions" ON public.hospital_config_versions FOR SELECT USING (true);
CREATE POLICY "Allow public read/insert/update access to runs" ON public.runs FOR ALL USING (true);
CREATE POLICY "Allow public read/insert/update access to answers" ON public.answers FOR ALL USING (true);
CREATE POLICY "Allow public access to web_verifications" ON public.web_verifications FOR ALL USING (true);
CREATE POLICY "Allow public access to web_verification_answers" ON public.web_verification_answers FOR ALL USING (true);

-- --------------------------------------------------------
-- Storage RLS (Row Level Security) Policies for 'lua_visibility_file'
-- --------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('lua_visibility_file', 'lua_visibility_file', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Allow public select on lua_visibility_file" ON storage.objects;
DROP POLICY IF EXISTS "Allow public insert on lua_visibility_file" ON storage.objects;
DROP POLICY IF EXISTS "Allow public update on lua_visibility_file" ON storage.objects;
DROP POLICY IF EXISTS "Allow public delete on lua_visibility_file" ON storage.objects;

CREATE POLICY "Allow public select on lua_visibility_file" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'lua_visibility_file');

CREATE POLICY "Allow public insert on lua_visibility_file" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'lua_visibility_file');

CREATE POLICY "Allow public update on lua_visibility_file" 
ON storage.objects FOR UPDATE 
USING (bucket_id = 'lua_visibility_file');

CREATE POLICY "Allow public delete on lua_visibility_file" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'lua_visibility_file');

